### ISSUE TITLE
Windows下编译不过

### ISSUE THREAD

**Issue by v4vendeta** [MengRao/fmtlog#16]
vs2019 

debug x64
![2](https://user-images.githubusercontent.com/45009841/141689943-1c3de86b-54d8-437d-af93-42d338173da2.png)

release x64
![1](https://user-images.githubusercontent.com/45009841/141689877-32289ce3-1ab3-4f53-89c7-aeec8dbc76d9.png)

**Comment by MengRao** [comment]
release的错误已经修复了，请更新下代码。
关于debug模式，由于cmake里面写死了/O2的编译选项，可能需要用户手动改下。

**Comment by v4vendeta** [comment]
多谢，已解决
