### ISSUE TITLE
Installation of header files

### ISSUE THREAD

**Issue by randomizedthinking** [MengRao/fmtlog#2]
The header files are not set to be installed by the cmake. It is a minor issue... but I feel it would be good to install header files in the system so users do not need to copy these files in their project directory manually.

**Comment by randomizedthinking** [comment]
A few additional comments:

- The shared/static library: can we remove shared from `libfmtlog-shared.so` and static from `libfmt-static.a`?
- The test utilities, such as log_test, link_static_static, etc, should not be installed to the system folders.

How do you think?

**Comment by MengRao** [comment]
Your comments make sense. Actually fmtlog is a pretty small project and I didn't take much time on cmake/installing scripting, the recommended building command is just running "./build.sh" which install libraries in the generated .build dir, and user can copy whatever he need to his destination path including header/library files(only two files need to be copied, 1 header + 1 lib or 2 headers), it should not be hard to operate.

**Comment by randomizedthinking** [comment]
Agree that it is easy item.

Here I'd like to use the thread to ask one more question. After reading the document, my understanding is that fmtlog lacks the support for multiple log files. Yet, in my use cases, multiple files are common scenarios. Is there any way we can bypass this issue?

**Comment by MengRao** [comment]
what do you mean by multiple files? Like Daily files in spdlog? or different files for different threads or something else?

**Comment by randomizedthinking** [comment]
I mean, in the program, the user can open multiple loggers and send output to multiple files.

**Comment by MengRao** [comment]
It's hard to acheive, because fmtlog makes heavy use of static and thread local variables, so there can only be one log instance in the program.

**Comment by randomizedthinking** [comment]
I see. Yet it is an important feature. Thanks for the wonderful package.
