### ISSUE TITLE
Feature suggestion: add a callback for logging threads (in addition to the async work callback)

### ISSUE THREAD

**Issue by gh-andre** [MengRao/fmtlog#28]
Current callback set with `fmtlog::setLogCB` is called from `fmtlog::poll`, which doesn't help in scheduling background asynchronous work done by `fmtlog::poll`. Consider adding a callback that would be called in the context of the logging thread based on some criteria, which could be used to queue a work request for the thread calling `fmtlog::poll`.

Consider a scenario in which `fmtlog::poll` is being called periodically (e.g. once a second) and keeps the logging buffer reasonably empty for new log messages. If a logging burst occurs that would overflow the buffer, some of the messages would be lost or blocking will occur, based on `FMTLOG_BLOCK`. If the frequency of `fmtlog::poll` is increased, it would be called unnecessarily most of the time, since logging bursts would happen rarely.

If there was a callback invoked in the logging thread context (i.e. from the call stack of `log` and `logOnce`), and this callback would have some call condition (e.g. when logger buffer is 50% full), it would be possible to use this callback to queue an asynchronous work request for the logger thread at the application level (i.e. outside of `fmtlog`), which would trigger `fmtlog::poll` call between regular polling intervals.

**Comment by MengRao** [comment]
Good suggestion. However the log queue is too simple to tell how much full it is: it can only know if it's full or not. If a callback is added when the queue is already full, it might not be useful as it's too late: it needs to notify and wait for the polling thread to flush the queue, so not a good solution.

**Comment by MengRao** [comment]
This feature is supported now, please check out the new api: `fmtlog::setLogQFullCB(cb)` and have a try, thanks.

**Comment by gh-andre** [comment]
Awesome. Thank you. I will try it out tomorrow and will let you know.

**Comment by gh-andre** [comment]
@MengRao Tested out new functionality and it works great. Thanks again.

I also merged the changes I use for my project, which includes these:

* CMake builds debug/release libraries (e.g. `assert` works as expected, debugging shows variables, etc)
* `FMTLOG_ONCE_LOCATION` is added to allow the caller to pass in actual location instead of the logging facility location (e.g. think a logger service - using current location only captures logging service location).
* GitHub action builds all platforms and runs tests. It currently is just helpful to see that all works, but may be extended to build per-OS packages.

You can see these changes here. If you are interested in any of them individually, let me know and I will create pull requests. Otherwise, will not mention this again.

https://github.com/gh-andre/fmtlog

I also can help you out to build a Nuget package for Windows, if you'd like. Let me know.

**Comment by gh-andre** [comment]
Sorry, ran into a problem with the callback - there's no user argument that can be passed in and it's defined in such a way that it's not possible to pass in a class with a function operator. Without one of these it's hard to integrate it into any logging facility.

**Comment by MengRao** [comment]
LogQFullCB is simply a global function pointer saved in fmtlog as same as LogCB, so there could only be one instance and user argument is not quite useful as global/static variables can be used in the callback. This callback is not designed in the C++ fashion so as to minimize performance cost, because low latency is the first priority in fmtlog design.

**Comment by gh-andre** [comment]
There's no performance degradation in adding an argument to a function call. It's just another variable that you pass in and you don't even need to check if it's been set or not. So, there's really no benefit in not providing it.

As for usefulness, keeping the argument variable in the logger allows callers to avoid using globals in their architecture. Keeps the code cleaner and leaves room for expansion. For example, you can add a logger handle to logging calls and this logger could be used in places that allow multiple applications per process, each with their own logger.

**Comment by MengRao** [comment]
emm... For adding user function arguments, the only generic way is to add a void pointer(which I dont think is elegant either), but if it can meet your needs I'll make the change.

**Comment by gh-andre** [comment]
Well, I would argue that it's more elegant than having a global on the caller's side :)

I think a `void` pointer will work out well for most people, including myself. It would be great if you could add it. Thanks.

For a more type-focused solution, you would need some type of a polymorphic callback handle and I would say that having such handle without having a multi-instance logger wouldn't be very practical, as you pointed out earlier. Could be a good feature for the backlog, though.

**Comment by MengRao** [comment]
Changes are done, please check.

**Comment by gh-andre** [comment]
Works great. Thank you!
