### ISSUE TITLE
Cmake error m1 MacBook

### ISSUE THREAD

**Issue by demhademha** [MengRao/fmtlog#29]
In file included from fmtlog.cc:1:
In file included from ./fmtlog-inl.h:24:
./fmtlog.h:272:14: error: use of undeclared identifier '__builtin_ia32_rdtsc'
      return __builtin_ia32_rdtsc();
             ^
1 error generated.

**Comment by MengRao** [comment]
Please check latest the code update and see if fixed, thanks.

**Comment by demhademha** [comment]
Issue fixed
Thanks
