### ISSUE TITLE
BufSize setting

### ISSUE THREAD

**Issue by randomizedthinking** [MengRao/fmtlog#3]
Fmtlog has achieved such a low latency yet with a much smaller throughput comparing to nanalog. I noticed that fmtlog is simply using the default BUFSIZE setting by the system (the default value is 8K), which could be the bottleneck to the overall throughput. It is one issue for spdlog as well.

Please checkout the issue in spdlog: https://github.com/gabime/spdlog/issues/1799. We can see that a reasonable BUFSIZ setting can double the throughput.

**Comment by MengRao** [comment]
Thanks for the suggestion. Though I dont have time testing/tunning the optimal BUFSIZ, we can always let the user make decision. And this is one of fmtlog's values: user should have the ability to tune the lib he is using.

I've added function `setFlushBufSize` for this.
