### ISSUE TITLE
FMT_NOEXCEPT是在哪儿定义的？

### ISSUE THREAD

**Issue by tilongzs** [MengRao/fmtlog#34]
fmtlog\fmtlog.h(97,40): error C3646: “FMT_NOEXCEPT”: 未知重写说明符

**Comment by MengRao** [comment]
在fmt/format.h里

**Comment by tilongzs** [comment]
里面并没有啊！你看下最新版的https://github.com/fmtlib/fmt.git是不是改了

**Comment by tilongzs** [comment]
哦，master的最新版是没了，[b6f4cea](https://github.com/fmtlib/fmt/tree/b6f4ceaed0a0a24ccf575fab6c56dd50ccf6f1a9)里还有。
