### ISSUE TITLE
对于windows的支持如何？

### ISSUE THREAD

**Issue by tilongzs** [MengRao/fmtlog#35]
在VisualStudio 2022下，控制台程序中使用了以下示例代码：

fmtlog::setLogFile("D:/log.txt", true);
	std::string str = "aaa";
	logi("str: {}, pstr: {}", str, &str);
	FMTLOG(fmtlog::INF, "The answer is {}.", 42);

	logi("A info msg");
	logd("This msg will not be logged as the default log level is INF");
	fmtlog::setLogLevel(fmtlog::DBG);
	logd("Now debug msg is shown");

但无论是调试窗口，还是log.txt中，都没有任何输出。请问哪里错了？

**Comment by MengRao** [comment]
需要周期性调用fmtlog::poll()才会输出，详见ReadMe.
