### ISSUE TITLE
Make CMakeLists.txt compatible with FetchContent

### ISSUE THREAD

**Issue by dirocco** [MengRao/fmtlog#4]
I'm working on revising the fmtlog CMakeLists.txt to work when calling FetchContent from another parent CMake project.  This allows people working with CMake to not have to know about git submodules when building a fresh project that has fmtlog as a dependency.

This mainly involves having fmtlog call FetchContent on fmtlib, to not build the tests when being built as a subproject, and to optionally build either the static or shared libraries.

Would you like a PR once it's cleaned up?

**Comment by MengRao** [comment]
Yeah, please submit a PR, thanks. Note that I recently upgraded fmt to 8.0.1
