### ISSUE TITLE
替换不安全的C代码吧

### ISSUE THREAD

**Issue by tilongzs** [MengRao/fmtlog#41]
通过VisualStudio使用C++17/C17标准编译时，报了以下错误：

> fmtlog-inl.h(564,5): error C4996: 'setbuf': This function or variable may be unsafe. Consider using setvbuf instead.
fmtlog-inl.h(546,17): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. 
fmtlog-inl.h(548,76): error C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. 
fmtlog-inl.h(276,27): error C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead.

**Comment by MengRao** [comment]
emm... 实际上如fopen之类的c函数非常跨平台通用且没有大问题，而fopen_s在非windows平台支持的并不好。所以如果调用api的程序本身没有使用错误可以忽略这些警告，具体做法可以参考这个链接：https://stackoverflow.com/a/21873153
