### ISSUE TITLE
writing multiple files from the logCB

### ISSUE THREAD

**Issue by TryAgain2019** [MengRao/fmtlog#48]
Hi,

In the logCB i write multiple files based on some index that i send with each logged message. 
Currently i write the index first and in the logCB i search for it through the message received. Then i convert to int, print remaining message to coresponding file...etc

Is there any more elegant way to do this, maybe with fmt::named tags and reading by name in the logCB?

thank you,

**Comment by TryAgain2019** [comment]
I've put that in the SPSCVarQueueOPT.MsgHeader along with logId and size. But not sure if it's the best thing since i break the perfect 64byte aligned MsgHeader :p

**Comment by MengRao** [comment]
You can also try splitting the uint32_t logId into two uint16_t, one for logId and one for the index, if the number of log statments is less than 65535
