### ISSUE TITLE
vformat_to

### ISSUE THREAD

**Issue by jacksionane** [MengRao/fmtlog#53]
fmtlog.h:601:51: error: missing template arguments before ‘(’ token
vformat_to(out, format, fmt::basic_format_args(args.data() + argIdx, num_args));

**Comment by MengRao** [comment]
please can you let me know what compiler you're using?

**Comment by jacksionane** [comment]
gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC)
