### ISSUE TITLE
日志时间戳乱序

### ISSUE THREAD

**Issue by GEM-VV** [MengRao/fmtlog#58]
尝试运行了test里的multithread_test.cc，日志时间戳会出现突然回退的情况
![微信截图_20221121082544](https://user-images.githubusercontent.com/68227298/202943856-9cd9d29a-5e49-41c9-99ca-953d2ed4ddbc.png)

**Comment by MengRao** [comment]
问下，你的运行系统是什么呢？另外multithread_test.cc，你有做哪些修改呢？

**Comment by GEM-VV** [comment]
CentOS 我就只在multithread_test.cc最前面加了#define FMTLOG_HEADER_ONLY 然后把fmtlog.h的路径改了 #include "fmtlog/fmtlog.h"

**Comment by MengRao** [comment]
默认的时间精度应该是微秒吧？这块有修改吗？

**Comment by GEM-VV** [comment]
> 默认的时间精度应该是微秒吧？这块有修改吗？

没改的话就只输出“12:23:25. test.cpp:31      INF[thread 0] msg : 0, i: 0”，我改成fmtlog::setHeaderPattern("{YmdHMSF} {s} {l}[{t}] ")之后也只有三位小数“22-11-21 12:25:34.704 test.cpp:31 INF[thread 0]”，会不会是我fmt库的版本有问题...

**Comment by MengRao** [comment]
不应该出现“12:23:25.”这种时间的，你的fmt版本是多少呢？

**Comment by GEM-VV** [comment]
之前我是先安的fmt 应该也是最新版的吧 刚我重新都又安了一遍 又没问题了 感谢！
