### ISSUE TITLE
能否支持一下日志分片功能，比如按天

### ISSUE THREAD

**Issue by zwc163** [MengRao/fmtlog#60]
1、能否支持一下日志分片功能，比如按天
2、时间错误问题，当程序运行跨天时，会出现第二天的时分秒为0

**Comment by MengRao** [comment]
你有试过log的时间输入日期吗？跨天后日期有正常变化吗？

**Comment by zwc163** [comment]
> 你有试过log的时间输入日期吗？跨天后日期有正常变化吗？

跨天后，日期变化正常，时分秒不正常

**Comment by zwc163** [comment]
> 你有试过log的时间输入日期吗？跨天后日期有正常变化吗？

日期变化正常，时分秒不正常

**Comment by MengRao** [comment]
跨天后，时分秒会长时间为0吗？有可能出现短暂为0的现象
