### ISSUE TITLE
[Question] Several logs output in one line in multithreaded application

### ISSUE THREAD

**Issue by Elnee** [MengRao/fmtlog#61]
I have a multithreaded application. Auto-polling is enabled with 1 second delay. I don't do any `fmtlog::poll()` calls manually in my code.

Sometimes I get strange output like that:
```
10:05:21.305388 web_socket_cli nmarket_data_server.cpp:439cketClient::WebSocketClien  INFcan[t17ni      ] itMarket data websocket client was created successfully with connection handler _key" : "..........................................................."
```

What am I doing wrong?

**Comment by MengRao** [comment]
how do you do the "auto polling"? did you run startPollingThread?

**Comment by Elnee** [comment]
@MengRao yes. And I managed to get consistent output in log file, but also I output to the console through callback. Callback body looking like this:

```
std::lock_guard< std::mutex > lock( callbackMutex_ );
std::cout << msg.data() << std::endl;
```

And sometimes I get one log string duplicated two times without newline character. Just in one line, including header with the same timestamp.

```
17:10:43.625878 web_socket_client.cpp:51 ERR[6443  ] Can't init asio with error code = invalid state17:10:43.625878 web_socket_client.cpp:51 ERR[6443  ] Can't init asio with error code = invalid state
```

**Comment by MengRao** [comment]
Did you run startPollingThread multiple times or in different threads? it should be run only once in a pragram.

**Comment by Elnee** [comment]
No. I only run startPollingThread once in the beginning of program.

I think the main problem is in the callback.

ср, 30 лист. 2022, 03:18 користувач Meng Rao ***@***.***>
пише:

**Comment by MengRao** [comment]
The data in callback is a fmt::string_view and doesn't have NULL at the end, you can use 
`std::cout << std::string_view(msg.data(), msg.size()) << std::endl;` instead.

**Comment by Elnee** [comment]
Yep, seems like its working. Sorry for disturbing. I'm very grateful for your help!
