### ISSUE TITLE
Could you plz add a new feature? Rotate every midnight.

### ISSUE THREAD

**Issue by JaydenFish** [MengRao/fmtlog#7]
Our team is developing a server software which is running 7x24. And we want the log rotate every midnight so it's easy to be analyzed. We dont need it rotate precisely 00:00:00. When log flush check the datetime to rotate.
There is a easy way. Add a callback in the flush function to user. Let user do it.

**Comment by MengRao** [comment]
you can simply call fmtlog::setLogFile() periodically with different filenames and it'll do as you wish. Also please update to the latest code asI just submitted a change related to this feature.

**Comment by JaydenFish** [comment]
that works! thank you!
