### ISSUE TITLE
求助，日志长时间运行，跨天后出现时分秒变成0

### ISSUE THREAD

**Issue by zwc163** [MengRao/fmtlog#72]
日志长时间运行，跨天后出现时分秒变成0，日期变化正确

**Comment by MengRao** [comment]
跨天后时分秒是短暂的变0还是长时间为0呢？

**Comment by zwc163** [comment]
> 跨天后时分秒是短暂的变0还是长时间为0呢？

长时间变为0，变为0后不再恢复正常，怀疑是切换CPU后，导致rtdsc返回的count不正确？

**Comment by MengRao** [comment]
你有周期性的poll吧？比如一秒一次

**Comment by zwc163** [comment]
> 你有周期性的poll吧？比如一秒一次

是的

**Comment by MengRao** [comment]
不跨日期的时候有发现过日志时间不递增（时间倒流）的情况吗？

**Comment by zwc163** [comment]
> 不跨日期的时候有发现过日志时间不递增（时间倒流）的情况吗？

没有

**Comment by MengRao** [comment]
这个问题有点奇怪，没有遇到过。你用的版本是最新的吧？可以稳定重现吗？

**Comment by zwc163** [comment]
> 这个问题有点奇怪，没有遇到过。你用的版本是最新的吧？可以稳定重现吗？

更正一下，不跨日期也会出现，稳定重现，但目前还没搞清楚规律。是去年11月份左右的版本

**Comment by MengRao** [comment]
你机器的cpu型号是什么？

**Comment by zwc163** [comment]
intel(R) xeon(R) CPU E5-2678 v3 2.5GHZ
我debug发现，handleLog函数里：int64_t ts = fmtlogWrapper<>::impl.tscns.tsc2ns(tsc);
ts有时是一个负数，ts=--7542113348780772001，tsc值看上去是正常的

**Comment by MengRao** [comment]
感觉像tscns在你机器上的问题，你可以用这个程序测试下（https://github.com/MengRao/tscns/blob/master/tscns_test.cc），看看有没有什么异常
