### ISSUE TITLE
有个办法,可以解决log里时间倒退的问题.

### ISSUE THREAD

**Issue by JaydenFish** [MengRao/fmtlog#8]
后端写log时,从所有线程的buf里取时间最小的处理.
用最小堆优化,可以做到 n*log(K), n是log数量,k是线程数量.
虽然比原来慢了些,但后端的性能没那么要紧.
在有些场合,log时间不倒退还是有用的.

**Comment by JaydenFish** [comment]
我觉得比起SPSC队列,每个线程用2个buffer可能会更好,一个用于前端写,另一个用于后端读,做个index指向,哪个是用于读的,另一个是用于写的.  当flush时,index翻转. 这样缓存失效更少,性能可能更好. 但坏处是更费内存.
这可能是个不成熟的想法,代码我还没研究完.

**Comment by MengRao** [comment]
第一个问题的最小堆的做法我也想过，但这也不能完全避免乱序。举个例子，log a和b先后分别入队列A和B，而server先读A后读B，A没读到数据，而B读到了，这样还是会先处理b。

第二个提议为什么会缓存失效更少呢，反而index每更新一次writer的index缓存就失效了，有可能更慢。

**Comment by MengRao** [comment]
关于第一个问题我重新思考了下，觉得做到基本保证多线程间时序就够了，至少比可能出现的严重乱序要好的多。修改已经提交，并release了v2.0.0。感谢提议。

**Comment by JaydenFish** [comment]
第二个问题请教一下,用SPSC_Queue, head和tail需要在2个线程间传递, 1个线程每修改一下,另一个线程的缓存行就失效了, 数据总是需要在2个线程间传递.每次延迟都会更高. 而 如果是2个buffer,就不会有这问题,但是翻转时缓存全部失效,会比较慢.
我理解得对吗? 哪种更好呢?

**Comment by MengRao** [comment]
问题不大，因为poll线程并不会非常频繁的读一个队列，只要writer没有正在写reader读取的那个cache line就不会有这个问题。另外就算缓存失效也不会影响前端延迟，因为前端是writer不是reader。
如果使用2个buffer就会发生reader让writer的缓存失效(index翻转），影响了前端延迟。
