### ISSUE TITLE
threading issue

### ISSUE THREAD

**Issue by clairemarconi** [MengRao/fmtlog#89]
When use following code to call runBenchmark() and set RECORDS in runBenchmark() to 1. The first print takes hundres of microseconds. Is there a way to keep logging thread hot internally?

  std::thread t([&]() { runBenchmark();runBenchmark();runBenchmark(); }); 
  t.join();

**Comment by MengRao** [comment]
From ReadMe: It's recommended that user actively calls fmt::preallocate() once the thread is created, so even the first log can have low latency
