### ISSUE TITLE
main函数里面写日志出现问题,看下面👇🏻

### ISSUE THREAD

**Issue by yangqun** [MengRao/fmtlog#93]
<img width="282" alt="image" src="https://github.com/MengRao/fmtlog/assets/5195784/5c65a90a-eff1-442d-887f-b4f62bd460eb">

while(1){
  FMTLOG(fmtlog::INF, "The answer is {}.", 42);
fmtlog::setHeaderPattern("[{HMSF}][{s}][{l}][{t}]:");
        fmtlog::setLogFile(logName);
        fmtlog::setLogLevel(levelEnum);
        fmtlog::poll();
sleep(10)
}

**Comment by MengRao** [comment]
sleep 10秒太长了，试试sleep 1秒?

**Comment by MengRao** [comment]
原因有点复杂，底层的时间同步程序需要不低于3秒一次的轮询频率，所以1秒poll一次比较合适。同时fmtlog::poll()的开销很低，基本可以忽略，所以poll频率高点对系统应该没有影响

**Comment by yangqun** [comment]
> 原因有点复杂，底层的时间同步程序需要不低于3秒一次的轮询频率，所以1秒poll一次比较合适。同时fmtlog::poll()的开销很低，基本可以忽略，所以poll频率高点对系统应该没有影响

谢谢大神回复。能大概指导一下应该去看源码哪一部分吗，前天晚上看了几个小时没找到原因，是时戳tsc那部分因为时间太长会变成0吗，也想追求进步呀。

**Comment by MengRao** [comment]
可以参考下tscns的文档：https://github.com/MengRao/tscns
![image](https://github.com/MengRao/fmtlog/assets/11496526/cf5dd5d0-3238-4406-a505-d779eda4f73c)
