### ISSUE TITLE
在静态库中使用会不会有问题呢

### ISSUE THREAD

**Issue by druidfund** [MengRao/fmtlog#95]
spdlog在静态库中使用会产生问题，
https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
请问fmtlog会不会也有这个问题呢？

**Comment by MengRao** [comment]
fmtlog会专门做一些简单的链接测试，包括头文件，静态库和动态库的使用，build项目时会创建如下测试程序：
![image](https://github.com/MengRao/fmtlog/assets/11496526/fa7ad183-aa7c-4c58-96cc-f97b287b4605)
目前还没遇到过使用fmtlog时有链接方面的问题，你可以自己测试一下:)

**Comment by druidfund** [comment]
目前使用没有问题，无缝替换spdlog，非常好的日志库
